services:
  ping-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - EMAIL=${EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - redis
    networks:
      - backend-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
